language: node_js
node_js:
  - stable

branches:
  only:
    - master

script:
  - npm test
  - npm run test:coverage

notifications:
  email:
    recipients:
      - ahmed.abdelhay.90@gmail.com
    on_success: always # default: change

